<a href="https://colab.research.google.com/github/areddysathvik/Transformer_Components/blob/main/attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [127]:
L,d_k,d_v = 4,10,10

K = np.random.randn(L,d_k)
Q = np.random.randn(L,d_v)
V = np.random.randn(L,d_v)

In [115]:
dt = K @ Q.T

In [42]:
K.var(),Q.var(),V.var(),dt.var()

(0.7171592691962955,
 0.46114107720190434,
 1.1683414989513496,
 4.303430384932198)

In [116]:
dt = dt / np.sqrt(d_k)

In [117]:
dt.var()

0.9722604237505874

In [118]:
import scipy

In [119]:
mask = np.tril(np.ones ((L,L)) )

mask[mask == 0] = -np.infty
mask[mask == 1] = 0

masked = mask + dt

masked

array([[-1.41307286,        -inf,        -inf,        -inf],
       [-0.27883346, -0.52441619,        -inf,        -inf],
       [ 0.46099882, -0.34021914,  1.01282492,        -inf],
       [ 1.93868286, -0.47914788, -1.00493997, -0.3738275 ]])

In [124]:
def softmax(x):
  return (np.exp(x).T / np.sum(np.exp(x), axis=-1)).T

attention = scipy.special.softmax(masked)

In [125]:
np.matmul(attention,V)

array([[-0.01059704, -0.01291357, -0.00451216,  0.00695956, -0.01196346,
        -0.02043801, -0.02489792,  0.01852363,  0.0128664 , -0.00756745],
       [-0.06023366, -0.05099197, -0.03966721,  0.1061174 , -0.03660663,
        -0.05810033, -0.04949574,  0.01144842, -0.01965042, -0.03853441],
       [ 0.13486884, -0.13286218, -0.08619847,  0.01988857, -0.32172938,
        -0.07103558, -0.16781587,  0.32046752, -0.25475584, -0.15392944],
       [-0.23393335, -0.36260397, -0.19598512,  0.28440495, -0.31846259,
        -0.58801015, -0.66571771,  0.49683879,  0.23537268, -0.26836059]])

In [126]:
V

array([[-0.66464539, -0.80993776, -0.28300235,  0.43650276, -0.75034707,
        -1.28187012, -1.56159576,  1.16180062,  0.80697965, -0.47462999],
       [-0.70382122, -0.2797328 , -0.66127302,  2.17885472,  0.01509972,
         0.14023845,  0.71975043, -1.18994116, -1.5384178 , -0.38708688],
       [ 1.31243307, -0.1978973 , -0.14402755, -0.70424136, -1.35556338,
         0.30813361, -0.21713419,  1.41525275, -1.47958788, -0.4800587 ],
       [ 1.45809959,  0.49270919, -0.81796076,  0.31467379,  1.22066963,
        -0.38881371,  0.47023306, -0.39325701, -0.75668526, -0.55625673]])